export PATH=$HOME/bin:/usr/local/bin:$PATH
export PATH=$PATH:$HOME/.cargo/bin
export PATH=$PATH:$HOME/.pyenv/bin

if test -z "${XDG_RUNTIME_DIR}"; then
	export XDG_RUNTIME_DIR=/tmp/${UID}-runtime-dir
	if ! test -d "${XDG_RUNTIME_DIR}"; then
		mkdir "${XDG_RUNTIME_DIR}"
		chmod 0700 "${XDG_RUNTIME_DIR}"
	fi
fi

# Common Configuration
export LANG=en_US.UTF-8

export EDITOR='nvim'
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
fi

# ZR - ZSH Plugin Manager written in rust
# Generate new ~/.zr/init.zsh whenever ~/.zshrc is modified
if [[ ! -f ~/.zr/init.zsh ]] || [[ ~/.zshrc -nt ~/.zr/init.zsh ]]; then
  zr load \
    lukechilds/zsh-nvm \
    paulmelnikow/zsh-startup-timer \
    willghatch/zsh-saneopt \
    zsh-users/zsh-autosuggestions \
    zsh-users/zsh-completions \
    zsh-users/zsh-syntax-highlighting \
    zsh-users/zsh-history-substring-search
fi
source ~/.zr/init.zsh

# Load zsh theme
source ~/.theme.zsh

# Keybindings for history substring search
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# Enable vim shortcuts in CLI
bindkey -v
set -o vi

# PyEnv Configuration
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
export PYENV_VIRTUALENVWRAPPER_PREFER_PYVENV="true"
pyenv virtualenvwrapper

# NPM Aliases
alias npml="npm list -depth 0" # Prints out all local installed dependencies
alias npmlg="npm list -depth 0 -g" # Prints out all global installed dependencies

# App Aliases
alias vi="vim"
alias vim="nvim"

alias ls="ls -G"
alias ll="ls -l"

#gentoo aliases
alias emerge="sudo emerge --ask"

# FZF init
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_COMMAND='fd --type f'
