export PATH=$HOME/bin:/usr/local/bin:$PATH
export PATH=$PATH:$HOME/.cargo/bin
export PATH=$PATH:$HOME/.pyenv/bin

# Common Configuration
export LANG=en_US.UTF-8
export ARCHFLAGS="-arch x86_64"
export EDITOR='nvim'
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
fi

# ZR - ZSH Plugin Manager written in rust
# Generate new ~/.zr/init.zsh whenever ~/.zshrc is modified
[[ ~/.zshrc -nt ~/.zr/init.zsh ]] && {
  zr load \
    ael-code/zsh-colored-man-pages \
    lukechilds/zsh-nvm \
    paulmelnikow/zsh-startup-timer \
    willghatch/zsh-saneopt \
    zsh-users/zsh-autosuggestions \
    zsh-users/zsh-completions \
    zsh-users/zsh-syntax-highlighting \
    zsh-users/zsh-history-substring-search \
    urbainvaes/fzf-marks \
}
source ~/.zr/init.zsh
source ~/.theme.zsh

# Keybindings for history substring search
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# Enable vim shortcuts in CLI
bindkey -v
set -o vi

# PyEnv Configuration
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
export PYENV_VIRTUALENVWRAPPER_PREFER_PYVENV="true"
pyenv virtualenvwrapper

# NPM Aliases
alias npml="npm list -depth 0" # Prints out all local installed dependencies
alias npmlg="npm list -depth 0 -g" # Prints out all global installed dependencies

# App Aliases
alias vim="nvim"
alias vi="nvim"

alias ls="ls -G"

# FZF init
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
